# Generated by Django 4.2.7 on 2025-11-04 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practicas', '0001_initial'),
        ('observaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='practica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='practicas.practica'),
        ),
    ]
