# Generated by Django 4.2.7 on 2025-11-04 22:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('rfc', models.CharField(max_length=13, unique=True, verbose_name='RFC')),
                ('razon_social', models.CharField(max_length=300, verbose_name='Razón Social')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('contacto_nombre', models.CharField(max_length=200, verbose_name='Nombre del Contacto')),
                ('contacto_puesto', models.CharField(max_length=100, verbose_name='Puesto del Contacto')),
                ('contacto_email', models.EmailField(max_length=254, verbose_name='Email del Contacto')),
                ('contacto_telefono', models.CharField(max_length=15, verbose_name='Teléfono del Contacto')),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector')),
                ('tamaño', models.CharField(blank=True, choices=[('MICRO', 'Micro (1-10 empleados)'), ('PEQUEÑA', 'Pequeña (11-50 empleados)'), ('MEDIANA', 'Mediana (51-250 empleados)'), ('GRANDE', 'Grande (251+ empleados)')], max_length=50, null=True, verbose_name='Tamaño')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('verificada', models.BooleanField(default=False, verbose_name='Verificada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('requisitos', models.TextField(verbose_name='Requisitos')),
                ('carreras_solicitadas', models.CharField(help_text='Carreras separadas por comas', max_length=500, verbose_name='Carreras Solicitadas')),
                ('semestre_minimo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Semestre Mínimo')),
                ('promedio_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Promedio Mínimo')),
                ('area', models.CharField(max_length=200, verbose_name='Área')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('REMOTO', 'Remoto'), ('HIBRIDO', 'Híbrido')], default='PRESENCIAL', max_length=50, verbose_name='Modalidad')),
                ('ubicacion', models.CharField(max_length=300, verbose_name='Ubicación')),
                ('horario', models.CharField(max_length=200, verbose_name='Horario')),
                ('duracion_meses', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración (meses)')),
                ('vacantes_disponibles', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Vacantes Disponibles')),
                ('vacantes_ocupadas', models.IntegerField(default=0, verbose_name='Vacantes Ocupadas')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_cierre_convocatoria', models.DateField(verbose_name='Fecha de Cierre de Convocatoria')),
                ('remunerada', models.BooleanField(default=False, verbose_name='Remunerada')),
                ('monto_apoyo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de Apoyo Mensual')),
                ('beneficios_adicionales', models.TextField(blank=True, null=True, verbose_name='Beneficios Adicionales')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('PAUSADA', 'Pausada'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacantes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='vacantes.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa', 'estado'], name='vacantes_va_empresa_85a81a_idx'), models.Index(fields=['estado', 'fecha_cierre_convocatoria'], name='vacantes_va_estado_c0e254_idx'), models.Index(fields=['created_at'], name='vacantes_va_created_9d151a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['rfc'], name='vacantes_em_rfc_df967a_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['nombre'], name='vacantes_em_nombre_e9390a_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['activa'], name='vacantes_em_activa_5e866c_idx'),
        ),
    ]
