# Generated by Django 5.2.8 on 2025-11-23 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='semestre_minimo',
            field=models.IntegerField(default=4, help_text='Semestre mínimo requerido (por defecto 4to semestre para prácticas profesionales)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Semestre Mínimo'),
        ),
    ]
