# Generated by Django 5.2.8 on 2025-11-23 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionMasiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFORMATIVA', 'Informativa'), ('IMPORTANTE', 'Importante'), ('URGENTE', 'Urgente'), ('RECORDATORIO', 'Recordatorio')], default='INFORMATIVA', max_length=20, verbose_name='Tipo')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('enviar_email', models.BooleanField(default=True, verbose_name='Enviar Email')),
                ('requiere_confirmacion', models.BooleanField(default=False, verbose_name='Requiere Confirmación')),
                ('enviada', models.BooleanField(default=False, verbose_name='Enviada')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('total_destinatarios', models.IntegerField(default=0, verbose_name='Total de Destinatarios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinatarios', models.ManyToManyField(limit_choices_to={'role': 'ESTUDIANTE'}, related_name='notificaciones_masivas_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatarios')),
                ('remitente', models.ForeignKey(limit_choices_to={'role': 'COORDINADORA_EMPRESARIAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_masivas_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Notificación Masiva',
                'verbose_name_plural': 'Notificaciones Masivas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFORMATIVA', 'Informativa'), ('IMPORTANTE', 'Importante'), ('URGENTE', 'Urgente'), ('RECORDATORIO', 'Recordatorio')], default='INFORMATIVA', max_length=20, verbose_name='Tipo')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('LEIDA', 'Leída')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('enviar_email', models.BooleanField(default=True, help_text='Enviar también por correo electrónico', verbose_name='Enviar Email')),
                ('requiere_confirmacion', models.BooleanField(default=False, help_text='El estudiante debe confirmar que leyó la notificación', verbose_name='Requiere Confirmación')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinatario', models.ForeignKey(help_text='Estudiante que recibirá la notificación', limit_choices_to={'role': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
                ('remitente', models.ForeignKey(limit_choices_to={'role': 'COORDINADORA_EMPRESARIAL'}, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinatario', 'estado'], name='notificacio_destina_458974_idx'), models.Index(fields=['remitente', 'fecha_envio'], name='notificacio_remiten_e3bd7f_idx'), models.Index(fields=['tipo', 'estado'], name='notificacio_tipo_6fa1b1_idx')],
            },
        ),
    ]
