# Generated by Django 4.2.7 on 2025-11-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SELECCIONADO', 'Seleccionado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('motivacion', models.TextField(verbose_name='Carta de Motivación')),
                ('fecha_seleccion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
