# Generated by Django 4.2.7 on 2025-11-04 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postulaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='seleccionado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selecciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='vacantes.vacante'),
        ),
        migrations.AlterUniqueTogether(
            name='postulacion',
            unique_together={('estudiante', 'vacante')},
        ),
    ]
