# Generated by Django 5.2.8 on 2025-11-23 20:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practicas', '0003_remove_practica_practicas_p_profeso_a55eb2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='entregables/%Y/%m/%d/', verbose_name='Archivo')),
                ('fecha_limite', models.DateTimeField(verbose_name='Fecha Límite de Entrega')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Entrega')),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Evaluación')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, help_text='Calificación del 0 al 100', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Calificación')),
                ('retroalimentacion', models.TextField(blank=True, help_text='Comentarios del tutor empresarial', null=True, verbose_name='Retroalimentación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('REVISADO', 'Revisado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(limit_choices_to={'role': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='entregables_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('evaluado_por', models.ForeignKey(blank=True, limit_choices_to={'role': 'TUTOR_EMPRESARIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregables_evaluados', to=settings.AUTH_USER_MODEL, verbose_name='Evaluado por')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='practicas.practica', verbose_name='Práctica')),
            ],
            options={
                'verbose_name': 'Entregable',
                'verbose_name_plural': 'Entregables',
                'ordering': ['-fecha_limite', '-created_at'],
                'indexes': [models.Index(fields=['practica', 'estado'], name='entregables_practic_59eddc_idx'), models.Index(fields=['estudiante', 'estado'], name='entregables_estudia_778729_idx'), models.Index(fields=['evaluado_por', 'estado'], name='entregables_evaluad_45ba3e_idx'), models.Index(fields=['fecha_limite'], name='entregables_fecha_l_256201_idx')],
            },
        ),
    ]
