# Generated by Django 4.2.7 on 2025-11-04 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacantes', '0001_initial'),
        ('practicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='asignada_por',
            field=models.ForeignKey(limit_choices_to={'role': 'COORDINADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignada por'),
        ),
        migrations.AddField(
            model_name='practica',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas', to='vacantes.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='practica',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'role': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='practica',
            name='profesor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PROFESOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_supervisadas', to=settings.AUTH_USER_MODEL, verbose_name='Profesor Asignado'),
        ),
        migrations.AddIndex(
            model_name='practica',
            index=models.Index(fields=['estudiante', 'estado'], name='practicas_p_estudia_80c932_idx'),
        ),
        migrations.AddIndex(
            model_name='practica',
            index=models.Index(fields=['profesor', 'estado'], name='practicas_p_profeso_a55eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='practica',
            index=models.Index(fields=['empresa', 'estado'], name='practicas_p_empresa_832557_idx'),
        ),
        migrations.AddIndex(
            model_name='practica',
            index=models.Index(fields=['estado', 'created_at'], name='practicas_p_estado_885ced_idx'),
        ),
        migrations.AddConstraint(
            model_name='practica',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['ASIGNADA', 'EN_CURSO'])), fields=('estudiante',), name='unique_active_practica_per_estudiante'),
        ),
    ]
