# Generated by Django 5.2.8 on 2025-11-23 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0002_initial'),
        ('vacantes', '0002_alter_vacante_semestre_minimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='practica',
            name='practicas_p_profeso_a55eb2_idx',
        ),
        migrations.RemoveField(
            model_name='practica',
            name='profesor',
        ),
        migrations.AddField(
            model_name='practica',
            name='cerrada_por',
            field=models.ForeignKey(blank=True, help_text='Coordinadora que cierra la práctica', limit_choices_to={'role': 'COORDINADORA_EMPRESARIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_cerradas', to=settings.AUTH_USER_MODEL, verbose_name='Cerrada por'),
        ),
        migrations.AddField(
            model_name='practica',
            name='docente_asesor',
            field=models.ForeignKey(blank=True, help_text='Docente que hace seguimiento al estudiante', limit_choices_to={'role': 'DOCENTE_ASESOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_asesoradas', to=settings.AUTH_USER_MODEL, verbose_name='Docente Asesor'),
        ),
        migrations.AddField(
            model_name='practica',
            name='fecha_sustentacion',
            field=models.DateTimeField(blank=True, help_text='Fecha programada por el docente asesor para la sustentación', null=True, verbose_name='Fecha de Sustentación'),
        ),
        migrations.AddField(
            model_name='practica',
            name='lugar_sustentacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar de Sustentación'),
        ),
        migrations.AddField(
            model_name='practica',
            name='observaciones_sustentacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de Sustentación'),
        ),
        migrations.AddField(
            model_name='practica',
            name='tutor_empresarial',
            field=models.ForeignKey(blank=True, help_text='Tutor de la empresa que evalúa al estudiante', limit_choices_to={'role': 'TUTOR_EMPRESARIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_tutoradas', to=settings.AUTH_USER_MODEL, verbose_name='Tutor Empresarial'),
        ),
        migrations.AlterField(
            model_name='practica',
            name='asignada_por',
            field=models.ForeignKey(limit_choices_to={'role': 'COORDINADORA_EMPRESARIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignada por'),
        ),
        migrations.AddIndex(
            model_name='practica',
            index=models.Index(fields=['docente_asesor', 'estado'], name='practicas_p_docente_36e294_idx'),
        ),
        migrations.AddIndex(
            model_name='practica',
            index=models.Index(fields=['tutor_empresarial', 'estado'], name='practicas_p_tutor_e_268240_idx'),
        ),
    ]
