# Generated by Django 5.2.8 on 2025-11-23 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practicas', '0003_remove_practica_practicas_p_profeso_a55eb2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SEGUIMIENTO', 'Reunión de Seguimiento'), ('SUSTENTACION', 'Sustentación')], default='SEGUIMIENTO', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('duracion_minutos', models.IntegerField(default=60, verbose_name='Duración (minutos)')),
                ('lugar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar')),
                ('enlace_virtual', models.URLField(blank=True, help_text='Enlace de videollamada (Zoom, Meet, Teams, etc.)', null=True, verbose_name='Enlace Virtual')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada')], default='PROGRAMADA', max_length=20, verbose_name='Estado')),
                ('notas_reunion', models.TextField(blank=True, help_text='Notas tomadas durante o después de la reunión', null=True, verbose_name='Notas de la Reunión')),
                ('acuerdos', models.TextField(blank=True, help_text='Acuerdos y compromisos tomados', null=True, verbose_name='Acuerdos')),
                ('estudiante_notificado', models.BooleanField(default=False, verbose_name='Estudiante Notificado')),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Notificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docente_asesor', models.ForeignKey(limit_choices_to={'role': 'DOCENTE_ASESOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='reuniones_programadas', to=settings.AUTH_USER_MODEL, verbose_name='Docente Asesor')),
                ('estudiante', models.ForeignKey(limit_choices_to={'role': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='reuniones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='practicas.practica', verbose_name='Práctica')),
            ],
            options={
                'verbose_name': 'Reunión',
                'verbose_name_plural': 'Reuniones',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['practica', 'estado'], name='reuniones_r_practic_1765a0_idx'), models.Index(fields=['docente_asesor', 'fecha_hora'], name='reuniones_r_docente_dd8c23_idx'), models.Index(fields=['estudiante', 'fecha_hora'], name='reuniones_r_estudia_50769e_idx'), models.Index(fields=['tipo', 'estado'], name='reuniones_r_tipo_47596f_idx')],
            },
        ),
    ]
