# Generated by Django 5.2.8 on 2025-11-23 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('vacantes', '0002_alter_vacante_semestre_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece el tutor empresarial', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutores_empresariales', to='vacantes.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='user',
            name='puesto',
            field=models.CharField(blank=True, help_text='Cargo del tutor en la empresa', max_length=200, null=True, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE_ASESOR', 'Docente Asesor'), ('TUTOR_EMPRESARIAL', 'Tutor Empresarial'), ('COORDINADORA_EMPRESARIAL', 'Coordinadora Empresarial')], default='ESTUDIANTE', max_length=30, verbose_name='Rol'),
        ),
    ]
