# Generated by Django 5.2.8 on 2025-11-24 16:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practicas', '0003_remove_practica_practicas_p_profeso_a55eb2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('dirigida_a', models.CharField(choices=[('ESTUDIANTES', 'Estudiantes'), ('TUTORES', 'Tutores Empresariales'), ('DOCENTES', 'Docentes Asesores'), ('TODOS', 'Todos los usuarios')], default='ESTUDIANTES', max_length=20, verbose_name='Dirigida a')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('es_anonima', models.BooleanField(default=False, verbose_name='Es anónima')),
                ('permite_multiple', models.BooleanField(default=False, verbose_name='Permitir responder múltiples veces')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto de la pregunta')),
                ('tipo', models.CharField(choices=[('TEXTO_CORTO', 'Texto Corto'), ('TEXTO_LARGO', 'Texto Largo'), ('OPCION_MULTIPLE', 'Opción Múltiple'), ('SELECCION_UNICA', 'Selección Única'), ('ESCALA', 'Escala (1-5)'), ('SI_NO', 'Sí/No')], default='TEXTO_CORTO', max_length=20, verbose_name='Tipo de pregunta')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('es_requerida', models.BooleanField(default=True, verbose_name='Es requerida')),
                ('opciones', models.JSONField(blank=True, help_text='Lista de opciones para preguntas de selección', null=True, verbose_name='Opciones')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='encuestas.encuesta', verbose_name='Encuesta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['encuesta', 'orden'],
                'unique_together': {('encuesta', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de respuesta')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.encuesta', verbose_name='Encuesta')),
                ('practica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_encuestas', to='practicas.practica', verbose_name='Práctica relacionada')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_encuestas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Respuesta de Encuesta',
                'verbose_name_plural': 'Respuestas de Encuestas',
                'ordering': ['-fecha_respuesta'],
            },
        ),
        migrations.CreateModel(
            name='DetallePregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField(blank=True, null=True, verbose_name='Respuesta de texto')),
                ('respuesta_numerica', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Respuesta numérica')),
                ('respuesta_booleana', models.BooleanField(blank=True, null=True, verbose_name='Respuesta Sí/No')),
                ('opciones_seleccionadas', models.JSONField(blank=True, null=True, verbose_name='Opciones seleccionadas')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.pregunta', verbose_name='Pregunta')),
                ('respuesta_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='encuestas.respuestaencuesta', verbose_name='Respuesta de encuesta')),
            ],
            options={
                'verbose_name': 'Detalle de Respuesta',
                'verbose_name_plural': 'Detalles de Respuestas',
                'unique_together': {('respuesta_encuesta', 'pregunta')},
            },
        ),
    ]
